### ISSUE TITLE
using just a single column is broken (hack provided)

### ISSUE THREAD

**Issue by ralfgoeke** [floriankarsten/kirby-tablex#11]
Hey Ho,
today I wanted to use tablex for a simple array-ish field, and discovered a bug:

if I just use a single column like this

```yaml
# blueprint
array2:
  type: tablex
  options:
    minColumns: 1
    maxColumns: 1
    header: false
```

the yaml is stored differently in the content file, compared to when I have two or more  columns

```yaml
# content file

# one column
table:
 - entry1
 - entry2

# two columns
table:
  - 
    - entry1a
    - entry1b
  - 
    - entry2a
    - entry2b
```

There's one empty array missing. And that results in a broken plugin frontend...
Every letter of the single columns text will be turned into a column itself (v-for gets a string instead of an array and loops happily over it)

I managed to find the problem and was able to hack it in tablex.php

```php
# tablex.php

public function result() {

  $result = parent::result();

  if(is_array($result['table'][0])) {
    return yaml::encode($result);
  } else {
    $res['table'] = [];
    foreach($result['table'] as $entry) {
      $res['table'][][] = $entry;
    }
    return yaml::encode($res);
  }
}
```

To be honest, I don't think this is a proper solution, since I suck at PHP pretty hard. But maybe my findings may help in a way...

Cheers, and thanx for the nice field. :)
